// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function GetAssetList() {
  return window['go']['main']['App']['GetAssetList']();
}

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetDiskInfo() {
  return window['go']['main']['App']['GetDiskInfo']();
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function GetMotherboardInfo() {
  return window['go']['main']['App']['GetMotherboardInfo']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetRAMInfo() {
  return window['go']['main']['App']['GetRAMInfo']();
}

export function GetWindowsInfo() {
  return window['go']['main']['App']['GetWindowsInfo']();
}

export function TestAsset(arg1) {
  return window['go']['main']['App']['TestAsset'](arg1);
}
