// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {software} from '../models';

export function CreateAsset(arg1:string):Promise<void>;

export function GetAssetList():Promise<Array<system.Asset>>;

export function GetCPUInfo():Promise<system.CPUInfo>;

export function GetDiskInfo():Promise<system.Disks>;

export function GetGPUInfo():Promise<system.GPUs>;

export function GetHwpInfo():Promise<software.HwpInfo>;

export function GetMotherboardInfo():Promise<system.MotherboardInfo>;

export function GetNetworkInfo():Promise<system.NetworkInfo>;

export function GetOfficeInfo():Promise<Array<software.OfficeInfo>>;

export function GetRAMInfo():Promise<system.RAMInfo>;

export function GetWindowsInfo():Promise<software.WindowsInfo>;

export function TestAsset(arg1:string):Promise<void>;
