// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';

export function CreateAsset(arg1:string):Promise<void>;

export function GetCPUInfo():Promise<system.CPUInfo>;

export function GetDiskInfo():Promise<system.Disks>;

export function GetGPUInfo():Promise<system.GPUs>;

export function GetMotherboardInfo():Promise<system.MotherboardInfo>;

export function GetNetworkInfo():Promise<system.NetworkInfo>;

export function GetRAMInfo():Promise<system.RAMInfo>;

export function TestAsset(arg1:string):Promise<void>;
